### PR TITLE
Remove duplicate commands?

### PR DESCRIPTION
**Pull request by d2dyno**
Dunno why these were duplicated. If this was intentional, just delete this PR.

### CODE REVIEW

**Comment by JMSDOnline** [comment]
we have to physically start/stop to create the `config.ini`. Otherwise the sed command fails with 'file doesn't exist'. Additionally, this causes no harm, nor does it produce a delay on the install.

**Comment by d2dyno** [comment]
I understand that completely. But why are we starting, stopping, starting again, stopping again, then sed?

**Comment by JMSDOnline** [comment]
The config.ini isn't creating itself on the first start/stop as it seems to only activate the systemd service, the next sequence gracefully starts the service and stops so we can successfully write to the config.ini

**Comment by d2dyno** [comment]
Ah, so I was just missing info 😂 my bad then.

**Comment by lizaSB** [comment]
It's possible that a 'sleep 5' might also do the trick. Starting and
stopping so quickly might not allow the app enough time to complete its
first boot and get the config made.

**Pull request closed without merging**
