### PR TITLE
merge master branch

### PR DESCRIPTION
**Pull request by amefs**
add new features
fix bugs

### CODE REVIEW

**Comment by JMSDOnline** [comment]
Sorry @amefs, I have been so busy with Pro I have overlooked a lot of Community PR and updates. Did you still want this submitted for further review?

**Comment by JMSDOnline** [comment]
Ah, I see. Nevermind. ;)

**Comment by amefs** [comment]
I need to clean up some my own code and recreate a new PR. I will fix some small bugs in installing qBittorrent, and update rtorrent 0.9.7.

**Comment by JMSDOnline** [comment]
Wonderful! Sounds great, thanks for your contributions. 
Also, could you DM quick me on the QuickBox Discord?

**Pull request closed without merging**
